imenu support
ALSchwalm/janet-mode pull request #1
Opened 2019-06-08 11:42 UTC by velkyel

2019-06-09 02:55 UTC, ALSchwalm requested changes
Thanks for the pull request! Just a couple of little things to address before I merge.

2019-06-09 02:55 UTC, ALSchwalm commented on janet-mode.el
> +     "^(\\(defn\\)*\\s-+(?\\(\\sw+\\)" 2)
I think I'd like this to be written in terms of `rx-to-string` like the rest of the regular expressions, just for clarity.

2019-06-09 02:55 UTC, ALSchwalm commented on janet-mode.el
> +  (setq-local imenu-syntax-alist '(("+-*/.<>=?!$%_&~^" . "w")))
If the matches in `janet-imenu-generic-expression` are written like the other patterns, I don't think we should need to make changes to the syntax table for imenu.

2019-06-09 03:09 UTC, ALSchwalm commented on janet-mode.el
> +     "^(\\(defn\\)*\\s-+(?\\(\\sw+\\)" 2)
Oh and for these I think we should probably also show private functions and macros (so `defn-` and `defmacro-`) as well.

2019-06-09 18:51 UTC, velkyel commented on janet-mode.el
> +     "^(\\(defn\\)*\\s-+(?\\(\\sw+\\)" 2)
ok, I'll include defn- and defmacro-.  I have to learn rx-to-string first..

2019-06-09 18:51 UTC, velkyel commented on janet-mode.el
> +  (setq-local imenu-syntax-alist '(("+-*/.<>=?!$%_&~^" . "w")))
you are right, imenu-syntax-alist is unnecessary.

2021-09-23 17:42 UTC, pierre-rouleau commented
@ ALSchwalm What's the status on this?  I'm starting to look at Janet and I'd like to get support going, including imenu support.  Not having imenu support breaks the prog-mode-hook.  Would it not be possible to allow this PR to go in and then modify it further?   I don't have much time but I might be able to help.

2021-09-24 00:48 UTC, ALSchwalm commented
imenu support has now been added in 9e3254a0249d720d5fa5603f1f8c3ed0612695af, so I'm gonna go ahead and close this

2021-09-24 00:48 UTC, closed without merging

2021-09-24 01:28 UTC, pierre-rouleau commented
> imenu support has now been added in [9e3254a](https://github.com/ALSchwalm/janet-mode/commit/9e3254a0249d720d5fa5603f1f8c3ed0612695af), so I'm gonna go ahead and close this

Thanks!